openapi: 3.2.0
info:
  title: DigitalOcean Droplet Autoscale Pools API
  version: '2.0'
  description: '# Introduction


    The DigitalOcean API allows you to manage Droplets and resources within the

    DigitalOcean cloud in a simple, programmatic way using conventional HTTP requests.'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: DigitalOcean API Team
    email: api-engineering@digitalocean.com
  termsOfService: https://www.digitalocean.com/legal/terms-of-service-agreement/
servers:
- url: https://api.digitalocean.com
  description: production
security:
- bearer_auth: []
tags:
- name: Droplet Autoscale Pools
  description: Droplet autoscale pools manage automatic horizontal scaling for your applications based on resource usage (CPU, memory, or both) or a static configuration.
paths:
  /v2/droplets/autoscale:
    get:
      operationId: autoscalepools_list
      summary: List All Autoscale Pools
      description: 'To list all autoscale pools in your team, send a GET request to `/v2/droplets/autoscale`.

        The response body will be a JSON object with a key of `autoscale_pools` containing an array of autoscale pool objects.

        These each contain the standard autoscale pool attributes.'
      tags:
      - Droplet Autoscale Pools
      parameters:
      - $ref: '#/components/parameters/per_page'
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/autoscale_pool_name'
      responses:
        '200':
          $ref: '#/components/responses/all_autoscale_pools'
        '401':
          $ref: '#/components/responses/unauthorized'
        '429':
          $ref: '#/components/responses/too_many_requests'
        '500':
          $ref: '#/components/responses/server_error'
        default:
          $ref: '#/components/responses/unexpected_error'
      x-codeSamples:
      - lang: cURL
        source: "curl -X GET \\\n  -H \"Content-Type: application/json\" \\\n  -H \"Authorization: Bearer $DIGITALOCEAN_TOKEN\" \\\n  \"https://api.digitalocean.com/v2/droplets/autoscale?page=1&per_page=1\""
      security:
      - bearer_auth:
        - droplet:read
    post:
      operationId: autoscalepools_create
      summary: Create a New Autoscale Pool
      description: 'To create a new autoscale pool, send a POST request to `/v2/droplets/autoscale` setting the required attributes.


        The response body will contain a JSON object with a key called `autoscale_pool` containing the standard attributes for the new autoscale pool.'
      tags:
      - Droplet Autoscale Pools
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/autoscale_pool_create'
            examples:
              Autoscale Create Request Dynamic Config:
                $ref: '#/components/examples/autoscale_create_request_dynamic'
              Autoscale Create Request Static Config:
                $ref: '#/components/examples/autoscale_create_request_static'
      responses:
        '202':
          $ref: '#/components/responses/autoscale_pool_create'
        '401':
          $ref: '#/components/responses/unauthorized'
        '429':
          $ref: '#/components/responses/too_many_requests'
        '500':
          $ref: '#/components/responses/server_error'
        default:
          $ref: '#/components/responses/unexpected_error'
      x-codeSamples:
      - lang: cURL
        source: "curl -X POST \\\n  -H \"Content-Type: application/json\" \\\n  -H \"Authorization: Bearer $DIGITALOCEAN_TOKEN\" \\\n  -d '{\n    \"name\": \"test-autoscalergroup\",\n    \"config\": {\n      \"min_instances\": 1,\n      \"max_instances\": 5,\n      \"target_cpu_utilization\": 0.5,\n      \"cooldown_minutes\": 5\n    },\n    \"droplet_template\": {\n      \"size\": \"c-2\",\n      \"region\": \"tor1\",\n      \"image\": \"ubuntu-20-04-x64\",\n      \"tags\": [\n        \"test-ag-01\"\n      ],\n      \"ssh_keys\": [\n        \"392594\",\n        \"385255\"\n      ],\n      \"vpc_uuid\": \"c472520a-831e-4770-8135-542c57a69daa\",\n      \"ipv6\": true,\n      \"user_data\": \"\\n#cloud-config\\nruncmd:\\n- apt-get update\\n\"\n    }\n  }' \\\n  \"https://api.digitalocean.com/v2/droplets/autoscale\""
      security:
      - bearer_auth:
        - droplet:create
  /v2/droplets/autoscale/{autoscale_pool_id}:
    get:
      operationId: autoscalepools_get
      summary: Retrieve an Existing Autoscale Pool
      description: 'To show information about an individual autoscale pool, send a GET request to

        `/v2/droplets/autoscale/$AUTOSCALE_POOL_ID`.'
      tags:
      - Droplet Autoscale Pools
      parameters:
      - $ref: '#/components/parameters/autoscale_pool_id'
      responses:
        '200':
          $ref: '#/components/responses/existing_autoscale_pool'
        '401':
          $ref: '#/components/responses/unauthorized'
        '404':
          $ref: '#/components/responses/not_found'
        '429':
          $ref: '#/components/responses/too_many_requests'
        '500':
          $ref: '#/components/responses/server_error'
        default:
          $ref: '#/components/responses/unexpected_error'
      x-codeSamples:
      - lang: cURL
        source: "curl -X GET \\\n  -H \"Content-Type: application/json\" \\\n  -H \"Authorization: Bearer $DIGITALOCEAN_TOKEN\" \\\n  \"https://api.digitalocean.com/v2/droplets/autoscale/880fee37-d07a-4f94-94a0-f07d9fc7bbb4\""
      security:
      - bearer_auth:
        - droplet:read
    put:
      operationId: autoscalepools_update
      summary: Update Autoscale Pool
      description: 'To update the configuration of an existing autoscale pool, send a PUT request to

        `/v2/droplets/autoscale/$AUTOSCALE_POOL_ID`. The request must contain a full representation

        of the autoscale pool including existing attributes.'
      tags:
      - Droplet Autoscale Pools
      parameters:
      - $ref: '#/components/parameters/autoscale_pool_id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/autoscale_pool_create'
            examples:
              Autoscale Update Request:
                $ref: '#/components/examples/autoscale_update_request'
      responses:
        '200':
          $ref: '#/components/responses/autoscale_pool_create'
        '401':
          $ref: '#/components/responses/unauthorized'
        '404':
          $ref: '#/components/responses/not_found'
        '429':
          $ref: '#/components/responses/too_many_requests'
        '500':
          $ref: '#/components/responses/server_error'
        default:
          $ref: '#/components/responses/unexpected_error'
      x-codeSamples:
      - lang: cURL
        source: "curl -X PUT \\\n  -H \"Content-Type: application/json\" \\\n  -H \"Authorization: Bearer $DIGITALOCEAN_TOKEN\" \\\n  -d '{\n    \"name\": \"test-autoscalergroup-01\",\n    \"config\": {\n      \"min_instances\": 1,\n      \"max_instances\": 5,\n      \"target_cpu_utilization\": 0.5,\n      \"cooldown_minutes\": 10\n    },\n    \"droplet_template\": {\n      \"size\": \"c-2\",\n      \"region\": \"tor1\",\n      \"image\": \"ubuntu-20-04-x64\",\n      \"tags\": [\n        \"test-ag-01\"\n      ],\n      \"ssh_keys\": [\n        \"372862\",\n        \"367582\",\n        \"355790\"\n      ],\n      \"vpc_uuid\": \"4637280e-3842-4661-a628-a6f0392959d3\",\n      \"with_droplet_agent\": true,\n      \"ipv6\": true,\n      \"user_data\": \"\\n#cloud-config\\nruncmd:\\n- apt-get update\\n\"\n    }\n  }' \\\n  \"https://api.digitalocean.com/v2/droplets/autoscale/d0067f19-c9bd-4d8c-b28b-e464fd1fb250\""
      security:
      - bearer_auth:
        - droplet:create
    delete:
      operationId: autoscalepools_delete
      summary: Delete autoscale pool
      description: 'To destroy an autoscale pool, send a DELETE request to the `/v2/droplets/autoscale/$AUTOSCALE_POOL_ID` endpoint.


        A successful response will include a 202 response code and no content.'
      tags:
      - Droplet Autoscale Pools
      parameters:
      - $ref: '#/components/parameters/autoscale_pool_id'
      responses:
        '202':
          $ref: '#/components/responses/no_content'
        '401':
          $ref: '#/components/responses/unauthorized'
        '404':
          $ref: '#/components/responses/not_found'
        '429':
          $ref: '#/components/responses/too_many_requests'
        '500':
          $ref: '#/components/responses/server_error'
        default:
          $ref: '#/components/responses/unexpected_error'
      x-codeSamples:
      - lang: cURL
        source: "curl -X DELETE \\\n  -H \"Content-Type: application/json\" \\\n  -H \"Authorization: Bearer $DIGITALOCEAN_TOKEN\" \\\n  \"https://api.digitalocean.com/v2/droplets/autoscale/880fee37-d07a-4f94-94a0-f07d9fc7bbb4\""
      security:
      - bearer_auth:
        - droplet:delete
  /v2/droplets/autoscale/{autoscale_pool_id}/dangerous:
    delete:
      operationId: autoscalepools_delete_dangerous
      summary: Delete autoscale pool and resources
      description: 'To destroy an autoscale pool and its associated resources (Droplets),

        send a DELETE request to the `/v2/droplets/autoscale/$AUTOSCALE_POOL_ID/dangerous` endpoint.'
      tags:
      - Droplet Autoscale Pools
      parameters:
      - $ref: '#/components/parameters/autoscale_pool_id'
      - $ref: '#/components/parameters/parameters_x_dangerous'
      responses:
        '202':
          $ref: '#/components/responses/no_content'
        '401':
          $ref: '#/components/responses/unauthorized'
        '404':
          $ref: '#/components/responses/not_found'
        '429':
          $ref: '#/components/responses/too_many_requests'
        '500':
          $ref: '#/components/responses/server_error'
        default:
          $ref: '#/components/responses/unexpected_error'
      x-codeSamples:
      - lang: cURL
        source: "curl -X DELETE \\\n  -H \"Content-Type: application/json\" \\\n  -H \"Authorization: Bearer $DIGITALOCEAN_TOKEN\" \\\n  -H \"X-Dangerous: true\" \\\n  \"https://api.digitalocean.com/v2/droplets/autoscale/880fee37-d07a-4f94-94a0-f07d9fc7bbb4/dangerous\""
      security:
      - bearer_auth:
        - droplet:delete
  /v2/droplets/autoscale/{autoscale_pool_id}/members:
    get:
      operationId: autoscalepools_list_members
      summary: List members
      description: 'To list the Droplets in an autoscale pool, send a GET request to `/v2/droplets/autoscale/$AUTOSCALE_POOL_ID/members`.


        The response body will be a JSON object with a key of `droplets`. This will be

        set to an array containing information about each of the Droplets in the autoscale pool.'
      tags:
      - Droplet Autoscale Pools
      parameters:
      - $ref: '#/components/parameters/per_page'
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/autoscale_pool_id'
      responses:
        '200':
          $ref: '#/components/responses/all_members'
        '401':
          $ref: '#/components/responses/unauthorized'
        '404':
          $ref: '#/components/responses/not_found'
        '429':
          $ref: '#/components/responses/too_many_requests'
        '500':
          $ref: '#/components/responses/server_error'
        default:
          $ref: '#/components/responses/unexpected_error'
      x-codeSamples:
      - lang: cURL
        source: "curl -X GET \\\n  -H \"Content-Type: application/json\" \\\n  -H \"Authorization: Bearer $DIGITALOCEAN_TOKEN\" \\\n  \"https://api.digitalocean.com/v2/droplets/autoscale/d0067f19-c9bd-4d8c-b28b-e464fd1fb250/members\""
      security:
      - bearer_auth:
        - droplet:read
  /v2/droplets/autoscale/{autoscale_pool_id}/history:
    get:
      operationId: autoscalepools_list_history
      summary: List history events
      description: 'To list all of the scaling history events of an autoscale pool, send a GET request to `/v2/droplets/autoscale/$AUTOSCALE_POOL_ID/history`.


        The response body will be a JSON object with a key of `history`. This will be

        set to an array containing objects each representing a history event.'
      tags:
      - Droplet Autoscale Pools
      parameters:
      - $ref: '#/components/parameters/per_page'
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/autoscale_pool_id'
      responses:
        '200':
          $ref: '#/components/responses/history_events'
        '401':
          $ref: '#/components/responses/unauthorized'
        '404':
          $ref: '#/components/responses/not_found'
        '429':
          $ref: '#/components/responses/too_many_requests'
        '500':
          $ref: '#/components/responses/server_error'
        default:
          $ref: '#/components/responses/unexpected_error'
      x-codeSamples:
      - lang: cURL
        source: "curl -X  GET \\\n  -H \"Content-Type: application/json\" \\\n  -H \"Authorization: Bearer $DIGITALOCEAN_TOKEN\" \\\n  \"https://api.digitalocean.com/v2/droplets/autoscale/07445b1b-1dc1-414d-b0a7-239ac66a9148/history\""
      security:
      - bearer_auth:
        - droplet:read
components:
  schemas:
    meta_properties:
      type: object
      description: Information about the response itself.
      properties:
        total:
          description: Number of objects returned by the request.
          type: integer
          example: 1
    link_to_last_page:
      type: object
      properties:
        last:
          description: URI of the last page of the results.
          type: string
          example: https://api.digitalocean.com/v2/images?page=2
    autoscale_pool_droplet_template:
      type: object
      properties:
        name:
          type: string
          example: my-droplet-name
          description: The name(s) to be applied to all Droplets in the autoscale pool.
        region:
          type: string
          example: tor1
          enum:
          - nyc1
          - nyc2
          - nyc3
          - ams2
          - ams3
          - sfo1
          - sfo2
          - sfo3
          - sgp1
          - lon1
          - fra1
          - tor1
          - blr1
          - syd1
          description: The datacenter in which all of the Droplets will be created.
        size:
          type: string
          example: c-2
          description: The Droplet size to be used for all Droplets in the autoscale pool.
        image:
          type: string
          example: ubuntu-20-04-x64
          description: The Droplet image to be used for all Droplets in the autoscale pool. You may specify the slug or the image ID.
        ssh_keys:
          type: array
          items:
            type: string
          example:
          - 88:66:90:d2:68:d5:b5:85:e3:26:26:11:31:57:e6:f8
          description: The SSH keys to be installed on the Droplets in the autoscale pool. You can either specify the key ID or the fingerprint.
        tags:
          type: array
          items:
            type: string
          example:
          - my-tag
          description: The tags to apply to each of the Droplets in the autoscale pool.
        vpc_uuid:
          type: string
          description: The VPC where the Droplets in the autoscale pool will be created. The VPC must be in the region where you want to create the Droplets.
          example: 760e09ef-dc84-11e8-981e-3cfdfeaae000
        with_droplet_agent:
          type: boolean
          description: Installs the Droplet agent. This must be set to true to monitor Droplets for resource utilization scaling.
          example: true
        project_id:
          type: string
          description: The project that the Droplets in the autoscale pool will belong to.
          example: 746c6152-2fa2-11ed-92d3-27aaa54e4988
        ipv6:
          type: boolean
          description: Assigns a unique IPv6 address to each of the Droplets in the autoscale pool.
          example: true
        user_data:
          type: string
          example: "#cloud-config\nruncmd:\n  - touch /test.txt\n"
          description: A string containing user data that cloud-init consumes to configure a Droplet on first boot. User data is often a cloud-config file or Bash script. It must be plain text and may not exceed 64 KiB in size.
      required:
      - region
      - image
      - size
      - ssh_keys
    error:
      type: object
      properties:
        id:
          description: A short identifier corresponding to the HTTP status code returned. For  example, the ID for a response returning a 404 status code would be "not_found."
          type: string
          example: not_found
        message:
          description: A message providing additional information about the error, including  details to help resolve it when possible.
          type: string
          example: The resource you were accessing could not be found.
        request_id:
          description: Optionally, some endpoints may include a request ID that should be  provided when reporting bugs or opening support tickets to help  identify the issue.
          type: string
          example: 4d9d8375-3c56-4925-a3e7-eb137fed17e9
      required:
      - id
      - message
    backward_links:
      allOf:
      - $ref: '#/components/schemas/link_to_first_page'
      - $ref: '#/components/schemas/link_to_prev_page'
    history:
      type: object
      properties:
        history_event_id:
          type: string
          example: 01936530-4471-7b86-9634-32d8fcfecbc6
          description: The unique identifier of the history event.
        current_instance_count:
          type: integer
          example: 2
          description: The current number of Droplets in the autoscale pool.
        desired_instance_count:
          type: integer
          example: 2
          description: The target number of Droplets for the autoscale pool after the scaling event.
        reason:
          type: string
          enum:
          - CONFIGURATION_CHANGE
          - SCALE_UP
          - SCALE_DOWN
          description: The reason for the scaling event.
          example: CONFIGURATION_CHANGE
        status:
          type: string
          enum:
          - in_progress
          - success
          - error
          description: The status of the scaling event.
          example: success
        created_at:
          format: date-time
          description: The creation time of the history event in ISO8601 combined date and time format.
          type: string
          example: '2020-07-28T18:00:00Z'
        updated_at:
          format: date-time
          description: The last updated time of the history event in ISO8601 combined date and time format.
          type: string
          example: '2020-07-28T18:00:00Z'
      required:
      - history_event_id
      - current_instance_count
      - desired_instance_count
      - reason
      - status
      - created_at
      - updated_at
    autoscale_pool_static_config:
      type: object
      properties:
        target_number_instances:
          title: static config
          type: integer
          example: 3
          description: Fixed number of instances in an autoscale pool.
          minimum: 1
          maximum: 1000
      required:
      - target_number_instances
    autoscale_pool:
      type: object
      properties:
        id:
          type: string
          example: 0d3db13e-a604-4944-9827-7ec2642d32ac
          description: A unique identifier for each autoscale pool instance. This is automatically generated upon autoscale pool creation.
        name:
          type: string
          example: my-autoscale-pool
          description: The human-readable name set for the autoscale pool.
        config:
          oneOf:
          - $ref: '#/components/schemas/autoscale_pool_static_config'
          - $ref: '#/components/schemas/autoscale_pool_dynamic_config'
          type: object
          description: The scaling configuration for an autoscale pool, which is how the pool scales up and down (either by resource utilization or static configuration).
        droplet_template:
          $ref: '#/components/schemas/autoscale_pool_droplet_template'
        current_utilization:
          $ref: '#/components/schemas/current_utilization'
        created_at:
          format: date-time
          title: The creation time of the autoscale pool
          type: string
          example: '2020-07-28T18:00:00Z'
          description: A time value given in ISO8601 combined date and time format that represents when the autoscale pool was created.
        updated_at:
          format: date-time
          title: When the autoscale pool was last updated
          type: string
          example: '2020-07-28T18:00:00Z'
          description: A time value given in ISO8601 combined date and time format that represents when the autoscale pool was last updated.
        status:
          type: string
          enum:
          - active
          - deleting
          - error
          description: The current status of the autoscale pool.
          example: active
        active_resources_count:
          type: integer
          example: 1
          description: The number of active Droplets in the autoscale pool.
      required:
      - id
      - name
      - config
      - droplet_template
      - created_at
      - updated_at
      - status
      - active_resources_count
    current_utilization:
      type: object
      properties:
        memory:
          type: number
          format: float
          example: 0.3588531587713522
          description: The average memory utilization of the autoscale pool.
          minimum: 0
          maximum: 1
        cpu:
          type: number
          format: float
          example: 0.0007338008770232183
          description: The average CPU utilization of the autoscale pool.
          minimum: 0
          maximum: 1
    autoscale_pool_dynamic_config:
      type: object
      properties:
        min_instances:
          type: integer
          example: 5
          description: The minimum number of Droplets in an autoscale pool.
          minimum: 1
          maximum: 500
        max_instances:
          type: integer
          example: 10
          description: The maximum number of Droplets in an autoscale pool.
          minimum: 1
          maximum: 1000
        target_cpu_utilization:
          type: number
          format: float
          example: 0.6
          description: Target CPU utilization as a decimal.
          minimum: 0.05
          maximum: 1
        target_memory_utilization:
          type: number
          format: float
          example: 0.6
          description: Target memory utilization as a decimal.
          minimum: 0.05
          maximum: 1
        cooldown_minutes:
          type: integer
          example: 5
          description: The number of minutes to wait between scaling events in an autoscale pool. Defaults to 10 minutes.
          minimum: 5
          maximum: 20
      required:
      - min_instances
      - max_instances
    meta:
      type: object
      properties:
        meta:
          allOf:
          - $ref: '#/components/schemas/meta_properties'
          - required:
            - total
      required:
      - meta
    link_to_next_page:
      type: object
      properties:
        next:
          description: URI of the next page of the results.
          type: string
          example: https://api.digitalocean.com/v2/images?page=2
    autoscale_pool_create:
      type: object
      properties:
        name:
          example: my-autoscale-pool
          type: string
          description: The human-readable name of the autoscale pool. This field cannot be updated
        config:
          oneOf:
          - $ref: '#/components/schemas/autoscale_pool_static_config'
          - $ref: '#/components/schemas/autoscale_pool_dynamic_config'
          type: object
          description: The scaling configuration for an autoscale pool, which is how the pool scales up and down (either by resource utilization or static configuration).
        droplet_template:
          $ref: '#/components/schemas/autoscale_pool_droplet_template'
      required:
      - name
      - config
      - droplet_template
    pagination:
      type: object
      properties:
        links:
          $ref: '#/components/schemas/page_links'
    member:
      type: object
      properties:
        droplet_id:
          type: integer
          example: 459903570
          description: The unique identifier of the Droplet.
        created_at:
          format: date-time
          description: The creation time of the Droplet in ISO8601 combined date and time format.
          type: string
          example: '2020-07-28T18:00:00Z'
        updated_at:
          format: date-time
          description: The last updated time of the Droplet in ISO8601 combined date and time format.
          type: string
          example: '2020-07-28T18:00:00Z'
        health_status:
          type: string
          example: active
          description: The health status of the Droplet.
        status:
          type: string
          enum:
          - provisioning
          - active
          - deleting
          - 'off'
          description: The power status of the Droplet.
          example: active
        current_utilization:
          $ref: '#/components/schemas/member_current_utilization'
      required:
      - droplet_id
      - created_at
      - updated_at
      - health_status
      - status
      - current_utilization
    page_links:
      type: object
      properties:
        pages:
          anyOf:
          - $ref: '#/components/schemas/forward_links'
          - $ref: '#/components/schemas/backward_links'
          - {}
          example:
            pages:
              first: https://api.digitalocean.com/v2/account/keys?page=1
              prev: https://api.digitalocean.com/v2/account/keys?page=2
    link_to_prev_page:
      type: object
      properties:
        prev:
          description: URI of the previous page of the results.
          type: string
          example: https://api.digitalocean.com/v2/images?page=1
    link_to_first_page:
      type: object
      properties:
        first:
          description: URI of the first page of the results.
          type: string
          example: https://api.digitalocean.com/v2/images?page=1
    forward_links:
      allOf:
      - $ref: '#/components/schemas/link_to_last_page'
      - $ref: '#/components/schemas/link_to_next_page'
    member_current_utilization:
      type: object
      properties:
        memory:
          type: number
          format: float
          example: 0.3588531587713522
          description: The memory utilization average of the individual Droplet.
        cpu:
          type: number
          format: float
          example: 0.0007338008770232183
          description: The CPU utilization average of the individual Droplet.
  responses:
    unexpected_error:
      description: Unexpected error
      headers:
        ratelimit-limit:
          $ref: '#/components/headers/ratelimit-limit'
        ratelimit-remaining:
          $ref: '#/components/headers/ratelimit-remaining'
        ratelimit-reset:
          $ref: '#/components/headers/ratelimit-reset'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
          example:
            id: example_error
            message: some error message
    no_content:
      description: The action was successful and the response body is empty.
      headers:
        ratelimit-limit:
          $ref: '#/components/headers/ratelimit-limit'
        ratelimit-remaining:
          $ref: '#/components/headers/ratelimit-remaining'
        ratelimit-reset:
          $ref: '#/components/headers/ratelimit-reset'
    not_found:
      description: The resource was not found.
      headers:
        ratelimit-limit:
          $ref: '#/components/headers/ratelimit-limit'
        ratelimit-remaining:
          $ref: '#/components/headers/ratelimit-remaining'
        ratelimit-reset:
          $ref: '#/components/headers/ratelimit-reset'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
          example:
            id: not_found
            message: The resource you requested could not be found.
    too_many_requests:
      description: API Rate limit exceeded
      headers:
        ratelimit-limit:
          $ref: '#/components/headers/ratelimit-limit'
        ratelimit-remaining:
          $ref: '#/components/headers/ratelimit-remaining'
        ratelimit-reset:
          $ref: '#/components/headers/ratelimit-reset'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
          example:
            id: too_many_requests
            message: API Rate limit exceeded.
    all_members:
      description: A JSON object with a key of `droplets`.
      headers:
        ratelimit-limit:
          $ref: '#/components/headers/ratelimit-limit'
        ratelimit-remaining:
          $ref: '#/components/headers/ratelimit-remaining'
        ratelimit-reset:
          $ref: '#/components/headers/ratelimit-reset'
      content:
        application/json:
          schema:
            allOf:
            - type: object
              properties:
                droplets:
                  type: array
                  items:
                    $ref: '#/components/schemas/member'
            - $ref: '#/components/schemas/pagination'
            - $ref: '#/components/schemas/meta'
          examples:
            All members:
              $ref: '#/components/examples/members_all'
    autoscale_pool_create:
      description: Accepted
      headers:
        ratelimit-limit:
          $ref: '#/components/headers/ratelimit-limit'
        ratelimit-remaining:
          $ref: '#/components/headers/ratelimit-remaining'
        ratelimit-reset:
          $ref: '#/components/headers/ratelimit-reset'
      content:
        application/json:
          schema:
            properties:
              autoscale_pool:
                $ref: '#/components/schemas/autoscale_pool'
          examples:
            Autoscale Create Response Dynamic Config:
              $ref: '#/components/examples/autoscale_create_response_dynamic'
            Autoscale Create Response Static Config:
              $ref: '#/components/examples/autoscale_create_response_static'
    unauthorized:
      description: Unauthorized
      headers:
        ratelimit-limit:
          $ref: '#/components/headers/ratelimit-limit'
        ratelimit-remaining:
          $ref: '#/components/headers/ratelimit-remaining'
        ratelimit-reset:
          $ref: '#/components/headers/ratelimit-reset'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
          example:
            id: unauthorized
            message: Unable to authenticate you.
    history_events:
      description: A JSON object with a key of `history`.
      headers:
        ratelimit-limit:
          $ref: '#/components/headers/ratelimit-limit'
        ratelimit-remaining:
          $ref: '#/components/headers/ratelimit-remaining'
        ratelimit-reset:
          $ref: '#/components/headers/ratelimit-reset'
      content:
        application/json:
          schema:
            allOf:
            - type: object
              properties:
                history:
                  type: array
                  items:
                    $ref: '#/components/schemas/history'
            - $ref: '#/components/schemas/pagination'
            - $ref: '#/components/schemas/meta'
          examples:
            All History Events:
              $ref: '#/components/examples/history_all'
    all_autoscale_pools:
      description: A JSON object with a key of `autoscale_pools`.
      headers:
        ratelimit-limit:
          $ref: '#/components/headers/ratelimit-limit'
        ratelimit-remaining:
          $ref: '#/components/headers/ratelimit-remaining'
        ratelimit-reset:
          $ref: '#/components/headers/ratelimit-reset'
      content:
        application/json:
          schema:
            allOf:
            - type: object
              properties:
                autoscale_pools:
                  type: array
                  items:
                    $ref: '#/components/schemas/autoscale_pool'
            - $ref: '#/components/schemas/pagination'
            - $ref: '#/components/schemas/meta'
          examples:
            All Autoscale Pools:
              $ref: '#/components/examples/autoscale_pools_all'
    existing_autoscale_pool:
      description: 'The response will be a JSON object with a key called `autoscale_pool`. This will be

        set to a JSON object that contains the standard autoscale pool attributes.

        '
      headers:
        ratelimit-limit:
          $ref: '#/components/headers/ratelimit-limit'
        ratelimit-remaining:
          $ref: '#/components/headers/ratelimit-remaining'
        ratelimit-reset:
          $ref: '#/components/headers/ratelimit-reset'
      content:
        application/json:
          schema:
            properties:
              autoscale_pool:
                $ref: '#/components/schemas/autoscale_pool'
          examples:
            Single Autoscale Pool:
              $ref: '#/components/examples/autoscale_pool_single'
    server_error:
      description: Server error.
      headers:
        ratelimit-limit:
          $ref: '#/components/headers/ratelimit-limit'
        ratelimit-remaining:
          $ref: '#/components/headers/ratelimit-remaining'
        ratelimit-reset:
          $ref: '#/components/headers/ratelimit-reset'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
          example:
            id: server_error
            message: Unexpected server-side error
  examples:
    autoscale_create_request_static:
      value:
        name: my-autoscale-pool
        config:
          target_number_instances: 2
        droplet_template:
          name: example.com
          region: nyc3
          size: c-2
          image: ubuntu-20-04-x64
          ssh_keys:
          - 3b:16:e4:bf:8b:00:8b:b8:59:8c:a9:d3:f0:19:fa:45
          backups: true
          ipv6: true
          monitoring: true
          tags:
          - env:prod
          - web
          user_data: "#cloud-config\nruncmd:\n  - touch /test.txt\n"
          vpc_uuid: 760e09ef-dc84-11e8-981e-3cfdfeaae000
    autoscale_pools_all:
      value:
        autoscale_pools:
        - id: 0d3db13e-a604-4944-9827-7ec2642d32ac
          name: test-autoscaler-group-01
          config:
            min_instances: 1
            max_instances: 5
            target_cpu_utilization: 0.5
            cooldown_minutes: 10
          droplet_template:
            name: droplet-name
            size: c-2
            region: tor1
            image: ubuntu-20-04-x64
            tags:
            - my-tag
            ssh_keys:
            - 3b:16:e4:bf:8b:00:8b:b8:59:8c:a9:d3:f0:19:fa:45
            vpc_uuid: 760e09ef-dc84-11e8-981e-3cfdfeaae000
            with_droplet_agent: true
            project_id: 746c6152-2fa2-11ed-92d3-27aaa54e4988
            ipv6: true
            user_data: "#cloud-config\nruncmd:\n  - touch /test.txt\n"
          created_at: '2020-11-19T20:27:18Z'
          updated_at: '2020-12-01T00:42:16Z'
          current_utilization:
            memory: 0.3588531587713522
            cpu: 0.0007338008770232183
          status: active
          active_resources_count: 1
        links:
          pages: null
        meta:
          total: 1
    members_all:
      value:
        droplets:
        - droplet_id: 123456
          created_at: '2020-11-19T20:27:18Z'
          updated_at: '2020-12-01T00:42:16Z'
          health_status: healthy
          status: active
          current_utilization:
            memory: 0.3588531587713522
            cpu: 0.0007338008770232183
        links:
          pages: null
        meta:
          total: 1
    autoscale_create_response_dynamic:
      value:
        autoscale_pool:
          id: 0d3db13e-a604-4944-9827-7ec2642d32ac
          name: test-autoscaler-group-01
          config:
            min_instances: 1
            max_instances: 5
            target_cpu_utilization: 0.5
            cooldown_minutes: 10
          droplet_template:
            name: droplet-name
            size: c-2
            region: tor1
            image: ubuntu-20-04-x64
            tags:
            - my-tag
            ssh_keys:
            - 3b:16:e4:bf:8b:00:8b:b8:59:8c:a9:d3:f0:19:fa:45
            vpc_uuid: 760e09ef-dc84-11e8-981e-3cfdfeaae000
            with_droplet_agent: true
            project_id: 746c6152-2fa2-11ed-92d3-27aaa54e4988
            ipv6: true
            user_data: "#cloud-config\nruncmd:\n  - touch /test.txt\n"
          created_at: '2020-11-19T20:27:18Z'
          updated_at: '2020-12-01T00:42:16Z'
          status: active
          active_resources_count: 1
    autoscale_pool_single:
      value:
        autoscale_pool:
          id: 0d3db13e-a604-4944-9827-7ec2642d32ac
          name: test-autoscaler-group-01
          config:
            min_instances: 1
            max_instances: 5
            target_cpu_utilization: 0.5
            cooldown_minutes: 10
          droplet_template:
            name: droplet-name
            size: c-2
            region: tor1
            image: ubuntu-20-04-x64
            tags:
            - my-tag
            ssh_keys:
            - 3b:16:e4:bf:8b:00:8b:b8:59:8c:a9:d3:f0:19:fa:45
            vpc_uuid: 760e09ef-dc84-11e8-981e-3cfdfeaae000
            with_droplet_agent: true
            project_id: 746c6152-2fa2-11ed-92d3-27aaa54e4988
            ipv6: true
            user_data: "#cloud-config\nruncmd:\n  - touch /test.txt\n"
          created_at: '2020-11-19T20:27:18Z'
          updated_at: '2020-12-01T00:42:16Z'
          current_utilization:
            memory: 0.3588531587713522
            cpu: 0.0007338008770232183
          status: active
          active_resources_count: 1
    autoscale_create_response_static:
      value:
        autoscale_pool:
          id: 0d3db13e-a604-4944-9827-7ec2642d32ac
          name: test-autoscaler-group-01
          config:
            target_number_instances: 1
          droplet_template:
            name: droplet-name
            size: c-2
            region: tor1
            image: ubuntu-20-04-x64
            tags:
            - my-tag
            ssh_keys:
            - 3b:16:e4:bf:8b:00:8b:b8:59:8c:a9:d3:f0:19:fa:45
            vpc_uuid: 760e09ef-dc84-11e8-981e-3cfdfeaae000
            with_droplet_agent: true
            project_id: 746c6152-2fa2-11ed-92d3-27aaa54e4988
            ipv6: true
            user_data: "#cloud-config\nruncmd:\n  - touch /test.txt\n"
          created_at: '2020-11-19T20:27:18Z'
          updated_at: '2020-12-01T00:42:16Z'
          status: active
          active_resources_count: 1
    autoscale_update_request:
      value:
        name: my-autoscale-pool
        config:
          target_number_instances: 2
        droplet_template:
          name: example.com
          region: nyc3
          size: c-2
          image: ubuntu-20-04-x64
          ssh_keys:
          - 3b:16:e4:bf:8b:00:8b:b8:59:8c:a9:d3:f0:19:fa:45
          backups: true
          ipv6: true
          monitoring: true
          tags:
          - env:prod
          - web
          user_data: "#cloud-config\nruncmd:\n  - touch /test.txt\n"
          vpc_uuid: 760e09ef-dc84-11e8-981e-3cfdfeaae000
    history_all:
      value:
        history:
        - history_event_id: 01936530-4471-7b86-9634-32d8fcfecbc6
          current_instance_count: 2
          desired_instance_count: 2
          reason: CONFIGURATION_CHANGE
          status: success
          created_at: '2020-11-19T20:27:18Z'
          updated_at: '2020-12-01T00:42:16Z'
        links:
          pages: null
        meta:
          total: 1
    autoscale_create_request_dynamic:
      value:
        name: my-autoscale-pool
        config:
          min_instances: 1
          max_instances: 5
          target_cpu_utilization: 0.5
          cooldown_minutes: 10
        droplet_template:
          name: example.com
          region: nyc3
          size: c-2
          image: ubuntu-20-04-x64
          ssh_keys:
          - 3b:16:e4:bf:8b:00:8b:b8:59:8c:a9:d3:f0:19:fa:45
          backups: true
          ipv6: true
          monitoring: true
          tags:
          - env:prod
          - web
          user_data: "#cloud-config\nruncmd:\n  - touch /test.txt\n"
          vpc_uuid: 760e09ef-dc84-11e8-981e-3cfdfeaae000
  parameters:
    autoscale_pool_name:
      name: name
      in: query
      description: The name of the autoscale pool
      schema:
        type: string
      example: my-autoscale-pool
    per_page:
      in: query
      name: per_page
      required: false
      description: Number of items returned per page
      schema:
        type: integer
        minimum: 1
        default: 20
        maximum: 200
      example: 2
    autoscale_pool_id:
      in: path
      name: autoscale_pool_id
      description: A unique identifier for an autoscale pool.
      required: true
      schema:
        type: string
      example: 0d3db13e-a604-4944-9827-7ec2642d32ac
    parameters_x_dangerous:
      in: header
      name: X-Dangerous
      description: Acknowledge this action will destroy the autoscale pool and its associated resources and _can not_ be reversed.
      schema:
        type: boolean
      example: true
      required: true
    page:
      in: query
      name: page
      required: false
      description: Which 'page' of paginated results to return.
      schema:
        type: integer
        minimum: 1
        default: 1
      example: 1
  headers:
    ratelimit-reset:
      schema:
        type: integer
      example: 1444931833
      description: The time when the oldest request will expire. The value is given in Unix epoch time. See https://developers.digitalocean.com/documentation/v2/#rate-limit for information about how requests expire.
    ratelimit-remaining:
      schema:
        type: integer
      example: 4816
      description: The number of requests in your hourly quota that remain before you hit your request limit. See https://developers.digitalocean.com/documentation/v2/#rate-limit for information about how requests expire.
    ratelimit-limit:
      schema:
        type: integer
      example: 5000
      description: The default limit on number of requests that can be made per hour and per minute. Current rate limits are 5000 requests per hour and 250 requests per minute.
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      description: '## OAuth Authentication


        In order to interact with the DigitalOcean API, you or your application must

        authenticate.


        The DigitalOcean API handles this through OAuth, an open standard for

        authorization. OAuth allows you to delegate access to your account.

        Scopes can be used to grant full access, read-only access, or access to

        a specific set of endpoints.


        You can generate an OAuth token by visiting the [Apps & API](https://cloud.digitalocean.com/account/api/tokens)

        section of the DigitalOcean control panel for your account.


        An OAuth token functions as a complete authentication request. In effect, it

        acts as a substitute for a username and password pair.


        Because of this, it is absolutely **essential** that you keep your OAuth

        tokens secure. In fact, upon generation, the web interface will only display

        each token a single time in order to prevent the token from being compromised.


        DigitalOcean access tokens begin with an identifiable prefix in order to

        distinguish them from other similar tokens.


        - `dop_v1_` for personal access tokens generated in the control panel

        - `doo_v1_` for tokens generated by applications using [the OAuth flow](https://docs.digitalocean.com/reference/api/oauth-api/)

        - `dor_v1_` for OAuth refresh tokens


        ### Scopes


        Scopes act like permissions assigned to an API token. These permissions

        determine what actions the token can perform. You can create API

        tokens that grant read-only access, full access, or limited access to

        specific endpoints by using custom scopes.


        Generally, scopes are designed to match HTTP verbs and common CRUD

        operations (Create, Read, Update, Delete).


        | HTTP Verb | CRUD Operation | Scope |

        |---|---|---|

        | GET | Read | `<resource>:read` |

        | POST | Create | `<resource>:create` |

        | PUT/PATCH | Update | `<resource>:update` |

        | DELETE | Delete | `<resource>:delete` |


        For example, creating a new Droplet by making a `POST` request to the

        `/v2/droplets` endpoint requires the `droplet:create` scope while

        listing Droplets by making a `GET` request to the `/v2/droplets`

        endpoint requires the `droplet:read` scope.


        Each endpoint below specifies which scope is required to access it when

        using custom scopes.


        ### How to Authenticate with OAuth


        In order to make an authenticated request, include a bearer-type

        `Authorization` header containing your OAuth token. All requests must be

        made over HTTPS.


        ### Authenticate with a Bearer Authorization Header


        ```

        curl -X $HTTP_METHOD -H "Authorization: Bearer $DIGITALOCEAN_TOKEN" "https://api.digitalocean.com/v2/$OBJECT"

        ```

        '
