openapi: 3.2.0
info:
  title: DigitalOcean Images API
  version: '2.0'
  description: '# Introduction


    The DigitalOcean API allows you to manage Droplets and resources within the

    DigitalOcean cloud in a simple, programmatic way using conventional HTTP requests.'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: DigitalOcean API Team
    email: api-engineering@digitalocean.com
  termsOfService: https://www.digitalocean.com/legal/terms-of-service-agreement/
servers:
- url: https://api.digitalocean.com
  description: production
security:
- bearer_auth: []
tags:
- name: Images
  description: 'A DigitalOcean image can be

    used to create a Droplet and may come in a number of flavors.'
paths:
  /v2/images:
    get:
      operationId: images_list
      summary: List All Images
      description: 'To list all of the images available on your account, send a GET request to /v2/images.


        ## Filtering Results

        -----


        It''s possible to request filtered results by including certain query parameters.


        **Image Type**


        Either 1-Click Application or OS Distribution images can be filtered by using the `type` query parameter.


        > Important: The `type` query parameter does not directly relate to the `type` attribute.


        To retrieve only ***distribution*** images, include the `type` query parameter set to distribution, `/v2/images?type=distribution`.


        To retrieve only ***application*** images, include the `type` query parameter set to application, `/v2/images?type=application`.


        **User Images**


        To retrieve only the private images of a user, include the `private` query parameter set to true, `/v2/images?private=true`.


        **Tags**


        To list all images assigned to a specific tag, include the `tag_name` query parameter set to the name of the tag in your GET request. For example, `/v2/images?tag_name=$TAG_NAME`.'
      tags:
      - Images
      parameters:
      - $ref: '#/components/parameters/type'
      - $ref: '#/components/parameters/private'
      - $ref: '#/components/parameters/tag'
      - $ref: '#/components/parameters/per_page'
      - $ref: '#/components/parameters/page'
      responses:
        '200':
          $ref: '#/components/responses/all_images'
        '401':
          $ref: '#/components/responses/unauthorized'
        '429':
          $ref: '#/components/responses/too_many_requests'
        '500':
          $ref: '#/components/responses/server_error'
        default:
          $ref: '#/components/responses/unexpected_error'
      x-codeSamples:
      - lang: cURL
        source: "curl -X GET \\\n  -H \"Content-Type: application/json\" \\\n  -H \"Authorization: Bearer $DIGITALOCEAN_TOKEN\" \\\n  \"https://api.digitalocean.com/v2/images?page=1&per_page=1\""
      - lang: Go
        source: "import (\n    \"context\"\n    \"os\"\n\n    \"github.com/digitalocean/godo\"\n)\n\nfunc main() {\n    token := os.Getenv(\"DIGITALOCEAN_TOKEN\")\n\n    client := godo.NewFromToken(token)\n    ctx := context.TODO()\n\n    opt := &godo.ListOptions{\n        Page:    1,\n        PerPage: 200,\n    }\n\n    // List all images\n    images, _, err := client.Images.List(ctx, opt)\n\n    // List all application images\n    opt := &godo.ListOptions{\n        Page:    1,\n        PerPage: 200,\n    }\n\n    images, _, err := client.Images.ListApplication(ctx, opt) \n}"
      - lang: Ruby
        source: 'require ''droplet_kit''

          token = ENV[''DIGITALOCEAN_TOKEN'']

          client = DropletKit::Client.new(access_token: token)


          # List all images

          images = client.images.all

          images.each


          # List all application images

          images = client.images.all(type: ''application'')

          images.each'
      - lang: Python
        source: 'import os

          from pydo import Client


          client = Client(token=os.environ.get("DIGITALOCEAN_TOKEN"))


          resp = client.images.list()'
      security:
      - bearer_auth:
        - image:read
    post:
      operationId: images_create_custom
      summary: Create a Custom Image
      description: 'To create a new custom image, send a POST request to /v2/images.

        The body must contain a url attribute pointing to a Linux virtual machine

        image to be imported into DigitalOcean.

        The image must be in the raw, qcow2, vhdx, vdi, or vmdk format.

        It may be compressed using gzip or bzip2 and must be smaller than 100 GB after

        being decompressed.'
      tags:
      - Images
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/image_new_custom'
      responses:
        '202':
          $ref: '#/components/responses/new_custom_image'
        '401':
          $ref: '#/components/responses/unauthorized'
        '429':
          $ref: '#/components/responses/too_many_requests'
        '500':
          $ref: '#/components/responses/server_error'
        default:
          $ref: '#/components/responses/unexpected_error'
      x-codeSamples:
      - lang: cURL
        source: "curl -X POST \\\n  -H \"Content-Type: application/json\" \\\n  -H \"Authorization: Bearer $DIGITALOCEAN_TOKEN\" \\\n  -d '{\"name\": \"ubuntu-18.04-minimal\", \"url\": \"http://cloud-images.ubuntu.com/minimal/releases/bionic/release/ubuntu-18.04-minimal-cloudimg-amd64.img\", \"distribution\": \"Ubuntu\", \"region\": \"nyc3\", \"description\": \"Cloud-optimized image w/ small footprint\", \"tags\":[\"base-image\", \"prod\"]}' \\\n  \"https://api.digitalocean.com/v2/images\""
      - lang: Python
        source: "import os\nfrom pydo import Client\n\nclient = Client(token=os.environ.get(\"DIGITALOCEAN_TOKEN\"))\n\nreq = {\n  \"name\": \"ubuntu-18.04-minimal\",\n  \"url\": \"http://cloud-images.ubuntu.com/minimal/releases/bionic/release/ubuntu-18.04-minimal-cloudimg-amd64.img\",\n  \"distribution\": \"Ubuntu\",\n  \"region\": \"nyc3\",\n  \"description\": \"Cloud-optimized image w/ small footprint\",\n  \"tags\": [\n    \"base-image\",\n    \"prod\"\n  ]\n}\n\nresp = client.images.create_custom(body=req)"
      security:
      - bearer_auth:
        - image:create
  /v2/images/{image_id}:
    get:
      operationId: images_get
      summary: Retrieve an Existing Image
      description: 'To retrieve information about an image, send a `GET` request to

        `/v2/images/$IDENTIFIER`.'
      tags:
      - Images
      parameters:
      - in: path
        name: image_id
        description: 'A unique number (id) or string (slug) used to identify and reference a

          specific image.


          **Public** images can be identified by image `id` or `slug`.


          **Private** images *must* be identified by image `id`.

          '
        required: true
        schema:
          anyOf:
          - type: integer
          - type: string
        examples:
          byId:
            summary: Retrieve a public or private image by id
            value: 62137902
          bySlug:
            summary: Retrieve a public image by slug
            value: ubuntu-16-04-x64
      responses:
        '200':
          $ref: '#/components/responses/existing_image'
        '401':
          $ref: '#/components/responses/unauthorized'
        '404':
          $ref: '#/components/responses/not_found'
        '429':
          $ref: '#/components/responses/too_many_requests'
        '500':
          $ref: '#/components/responses/server_error'
        default:
          $ref: '#/components/responses/unexpected_error'
      x-codeSamples:
      - lang: cURL
        source: "# Get existing image by ID\ncurl -X GET \\\n  -H \"Content-Type: application/json\" \\\n  -H \"Authorization: Bearer $DIGITALOCEAN_TOKEN\" \\\n  \"https://api.digitalocean.com/v2/images/7555620\"\n\n# Get existing image by slug\ncurl -X GET \\\n  -H \"Content-Type: application/json\" \\\n  -H \"Authorization: Bearer $DIGITALOCEAN_TOKEN\" \\\n  \"https://api.digitalocean.com/v2/images/ubuntu-16-04-x64\""
      - lang: Go
        source: "import (\n    \"context\"\n    \"os\"\n\n    \"github.com/digitalocean/godo\"\n)\n\nfunc main() {\n    token := os.Getenv(\"DIGITALOCEAN_TOKEN\")\n\n    client := godo.NewFromToken(token)\n    ctx := context.TODO()\n\n    // Get existing image by ID\n    image, _, err := client.Images.GetByID(ctx, 7555620)\n\n    // Get existing image by slug\n    // image, _, err := client.Images.GetBySlug(ctx, \"ubuntu-16-04-x64\") \n}"
      - lang: Ruby
        source: 'require ''droplet_kit''

          token = ENV[''DIGITALOCEAN_TOKEN'']

          client = DropletKit::Client.new(access_token: token)


          # Retrieve image by ID

          client.images.find(id: ''7555620'')


          # Retrieve image by slug

          client.images.find(id: ''ubuntu-16-04-x64'')'
      - lang: Python
        source: 'import os

          from pydo import Client


          client = Client(token=os.environ.get("DIGITALOCEAN_TOKEN"))


          resp = client.images.get(image_id=134215)'
      security:
      - bearer_auth:
        - image:read
    put:
      operationId: images_update
      summary: Update an Image
      description: 'To update an image, send a `PUT` request to `/v2/images/$IMAGE_ID`.

        Set the `name` attribute to the new value you would like to use.

        For custom images, the `description` and `distribution` attributes may also be updated.'
      tags:
      - Images
      parameters:
      - $ref: '#/components/parameters/image_id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/image_update'
      responses:
        '200':
          $ref: '#/components/responses/updated_image'
        '401':
          $ref: '#/components/responses/unauthorized'
        '404':
          $ref: '#/components/responses/not_found'
        '429':
          $ref: '#/components/responses/too_many_requests'
        '500':
          $ref: '#/components/responses/server_error'
        default:
          $ref: '#/components/responses/unexpected_error'
      x-codeSamples:
      - lang: cURL
        source: "curl -X PUT \\\n  -H \"Content-Type: application/json\" \\\n  -H \"Authorization: Bearer $DIGITALOCEAN_TOKEN\" \\\n  -d '{\"name\":\"new-image-name\"}' \\\n  \"https://api.digitalocean.com/v2/images/7938391\""
      - lang: Go
        source: "import (\n    \"context\"\n    \"os\"\n\n    \"github.com/digitalocean/godo\"\n)\n\nfunc main() {\n    token := os.Getenv(\"DIGITALOCEAN_TOKEN\")\n\n    client := godo.NewFromToken(token)\n    ctx := context.TODO()\n\n    updateRequest := &godo.ImageUpdateRequest{\n        Name: \"new-image-name\",\n    }\n\n    image, _, err := client.Images.Update(ctx, id, updateRequest)\n}"
      - lang: Ruby
        source: 'require ''droplet_kit''

          token = ENV[''DIGITALOCEAN_TOKEN'']

          client = DropletKit::Client.new(access_token: token)


          image = DropletKit::Image.new(name: ''new-image-name'')

          client.images.update(image, id: 7938391)'
      - lang: Python
        source: "import os\nfrom pydo import Client\n\nclient = Client(token=os.environ.get(\"DIGITALOCEAN_TOKEN\"))\n\nreq = {\n  \"name\": \"Nifty New Snapshot\",\n  \"distribution\": \"Ubuntu\",\n  \"description\": \" \"\n}\n\nresp = client.images.update(image_id=234532, body=req)"
      security:
      - bearer_auth:
        - image:update
    delete:
      operationId: images_delete
      summary: Delete an Image
      description: To delete a snapshot or custom image, send a `DELETE` request to `/v2/images/$IMAGE_ID`.
      tags:
      - Images
      parameters:
      - $ref: '#/components/parameters/image_id'
      responses:
        '204':
          $ref: '#/components/responses/no_content'
        '401':
          $ref: '#/components/responses/unauthorized'
        '404':
          $ref: '#/components/responses/not_found'
        '429':
          $ref: '#/components/responses/too_many_requests'
        '500':
          $ref: '#/components/responses/server_error'
        default:
          $ref: '#/components/responses/unexpected_error'
      x-codeSamples:
      - lang: cURL
        source: "curl -X DELETE \\\n  -H \"Content-Type: application/json\" \\\n  -H \"Authorization: Bearer $DIGITALOCEAN_TOKEN\" \\\n  \"https://api.digitalocean.com/v2/images/7938391\""
      - lang: Go
        source: "import (\n    \"context\"\n    \"os\"\n\n    \"github.com/digitalocean/godo\"\n)\n\nfunc main() {\n    token := os.Getenv(\"DIGITALOCEAN_TOKEN\")\n\n    client := godo.NewFromToken(token)\n    ctx := context.TODO()\n\n    _, err := client.Images.Delete(ctx, 7938391)\n}"
      - lang: Ruby
        source: 'require ''droplet_kit''

          token = ENV[''DIGITALOCEAN_TOKEN'']

          client = DropletKit::Client.new(access_token: token)


          client.images.delete(id: 7938391)'
      - lang: Python
        source: 'import os

          from pydo import Client


          client = Client(token=os.environ.get("DIGITALOCEAN_TOKEN"))


          resp = client.images.delete(image_id=134215)'
      security:
      - bearer_auth:
        - image:delete
components:
  schemas:
    meta_properties:
      type: object
      description: Information about the response itself.
      properties:
        total:
          description: Number of objects returned by the request.
          type: integer
          example: 1
    link_to_last_page:
      type: object
      properties:
        last:
          description: URI of the last page of the results.
          type: string
          example: https://api.digitalocean.com/v2/images?page=2
    image:
      type: object
      properties:
        id:
          type: integer
          description: A unique number that can be used to identify and reference a specific image.
          example: 7555620
          readOnly: true
        name:
          $ref: '#/components/schemas/image_name'
        type:
          type: string
          description: Describes the kind of image. It may be one of `base`, `snapshot`, `backup`, `custom`, or `admin`. Respectively, this specifies whether an image is a DigitalOcean base OS image, user-generated Droplet snapshot, automatically created Droplet backup, user-provided virtual machine image, or an image used for DigitalOcean managed resources (e.g. DOKS worker nodes).
          enum:
          - base
          - snapshot
          - backup
          - custom
          - admin
          example: snapshot
        distribution:
          $ref: '#/components/schemas/distribution'
        slug:
          type:
          - string
          - 'null'
          description: A uniquely identifying string that is associated with each of the DigitalOcean-provided public images. These can be used to reference a public image as an alternative to the numeric id.
          example: nifty1
        public:
          type: boolean
          description: This is a boolean value that indicates whether the image in question is public or not. An image that is public is available to all accounts. A non-public image is only accessible from your account.
          example: true
        regions:
          $ref: '#/components/schemas/regions_array'
        created_at:
          type: string
          format: date-time
          description: A time value given in ISO8601 combined date and time format that represents when the image was created.
          example: '2020-05-04T22:23:02Z'
        min_disk_size:
          type:
          - integer
          - 'null'
          description: The minimum disk size in GB required for a Droplet to use this image.
          example: 20
          minimum: 0
        size_gigabytes:
          type:
          - number
          - 'null'
          format: float
          description: The size of the image in gigabytes.
          example: 2.34
        description:
          $ref: '#/components/schemas/image_description'
        tags:
          $ref: '#/components/schemas/tags_array'
        status:
          type: string
          description: "A status string indicating the state of a custom image. This may be `NEW`,\n `available`, `pending`, `deleted`, or `retired`."
          enum:
          - NEW
          - available
          - pending
          - deleted
          - retired
          example: NEW
        error_message:
          type: string
          description: "A string containing information about errors that may occur when importing\n a custom image."
          example: ' '
    distribution:
      type: string
      description: The name of a custom image's distribution. Currently, the valid values are  `Arch Linux`, `CentOS`, `CoreOS`, `Debian`, `Fedora`, `Fedora Atomic`,  `FreeBSD`, `Gentoo`, `openSUSE`, `RancherOS`, `Rocky Linux`, `Ubuntu`, and `Unknown`.  Any other value will be accepted but ignored, and `Unknown` will be used in its place.
      enum:
      - Arch Linux
      - CentOS
      - CoreOS
      - Debian
      - Fedora
      - Fedora Atomic
      - FreeBSD
      - Gentoo
      - openSUSE
      - RancherOS
      - Rocky Linux
      - Ubuntu
      - Unknown
      example: Ubuntu
    error:
      type: object
      properties:
        id:
          description: A short identifier corresponding to the HTTP status code returned. For  example, the ID for a response returning a 404 status code would be "not_found."
          type: string
          example: not_found
        message:
          description: A message providing additional information about the error, including  details to help resolve it when possible.
          type: string
          example: The resource you were accessing could not be found.
        request_id:
          description: Optionally, some endpoints may include a request ID that should be  provided when reporting bugs or opening support tickets to help  identify the issue.
          type: string
          example: 4d9d8375-3c56-4925-a3e7-eb137fed17e9
      required:
      - id
      - message
    image_new_custom:
      type: object
      allOf:
      - $ref: '#/components/schemas/image_update'
      - properties:
          url:
            type: string
            description: A URL from which the custom Linux virtual machine image may be retrieved.  The image it points to must be in the raw, qcow2, vhdx, vdi, or vmdk format.  It may be compressed using gzip or bzip2 and must be smaller than 100 GB after being decompressed.
            example: http://cloud-images.ubuntu.com/minimal/releases/bionic/release/ubuntu-18.04-minimal-cloudimg-amd64.img
          region:
            $ref: '#/components/schemas/region_slug'
          tags:
            $ref: '#/components/schemas/tags_array'
      required:
      - name
      - url
      - region
      example:
        name: ubuntu-18.04-minimal
        url: http://cloud-images.ubuntu.com/minimal/releases/bionic/release/ubuntu-18.04-minimal-cloudimg-amd64.img
        distribution: Ubuntu
        region: nyc3
        description: Cloud-optimized image w/ small footprint
        tags:
        - base-image
        - prod
    backward_links:
      allOf:
      - $ref: '#/components/schemas/link_to_first_page'
      - $ref: '#/components/schemas/link_to_prev_page'
    image_name:
      type: string
      description: The display name that has been given to an image.  This is what is shown in the control panel and is generally a descriptive title for the image in question.
      example: Nifty New Snapshot
    image_description:
      type: string
      description: An optional free-form text field to describe an image.
      example: ' '
    tags_array:
      type:
      - array
      - 'null'
      items:
        type: string
      description: A flat array of tag names as strings to be applied to the resource. Tag names may be for either existing or new tags.
      example:
      - base-image
      - prod
    meta:
      type: object
      properties:
        meta:
          allOf:
          - $ref: '#/components/schemas/meta_properties'
          - required:
            - total
      required:
      - meta
    link_to_next_page:
      type: object
      properties:
        next:
          description: URI of the next page of the results.
          type: string
          example: https://api.digitalocean.com/v2/images?page=2
    pagination:
      type: object
      properties:
        links:
          $ref: '#/components/schemas/page_links'
    image_update:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/image_name'
        distribution:
          $ref: '#/components/schemas/distribution'
        description:
          $ref: '#/components/schemas/image_description'
    link_to_prev_page:
      type: object
      properties:
        prev:
          description: URI of the previous page of the results.
          type: string
          example: https://api.digitalocean.com/v2/images?page=1
    region_slug:
      type: string
      description: The slug identifier for the region where the resource will initially be  available.
      enum:
      - ams1
      - ams2
      - ams3
      - blr1
      - fra1
      - lon1
      - nyc1
      - nyc2
      - nyc3
      - sfo1
      - sfo2
      - sfo3
      - sgp1
      - tor1
      - syd1
      example: nyc3
    link_to_first_page:
      type: object
      properties:
        first:
          description: URI of the first page of the results.
          type: string
          example: https://api.digitalocean.com/v2/images?page=1
    forward_links:
      allOf:
      - $ref: '#/components/schemas/link_to_last_page'
      - $ref: '#/components/schemas/link_to_next_page'
    page_links:
      type: object
      properties:
        pages:
          anyOf:
          - $ref: '#/components/schemas/forward_links'
          - $ref: '#/components/schemas/backward_links'
          - {}
          example:
            pages:
              first: https://api.digitalocean.com/v2/account/keys?page=1
              prev: https://api.digitalocean.com/v2/account/keys?page=2
    regions_array:
      type: array
      items:
        $ref: '#/components/schemas/region_slug'
      description: This attribute is an array of the regions that the image is available in. The regions are represented by their identifying slug values.
      example:
      - nyc1
      - nyc2
  responses:
    unexpected_error:
      description: Unexpected error
      headers:
        ratelimit-limit:
          $ref: '#/components/headers/ratelimit-limit'
        ratelimit-remaining:
          $ref: '#/components/headers/ratelimit-remaining'
        ratelimit-reset:
          $ref: '#/components/headers/ratelimit-reset'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
          example:
            id: example_error
            message: some error message
    no_content:
      description: The action was successful and the response body is empty.
      headers:
        ratelimit-limit:
          $ref: '#/components/headers/ratelimit-limit'
        ratelimit-remaining:
          $ref: '#/components/headers/ratelimit-remaining'
        ratelimit-reset:
          $ref: '#/components/headers/ratelimit-reset'
    all_images:
      description: The response will be a JSON object with a key called `images`.  This will be set to an array of image objects, each of which will contain the standard image attributes.
      headers:
        ratelimit-limit:
          $ref: '#/components/headers/ratelimit-limit'
        ratelimit-remaining:
          $ref: '#/components/headers/ratelimit-remaining'
        ratelimit-reset:
          $ref: '#/components/headers/ratelimit-reset'
      content:
        application/json:
          schema:
            allOf:
            - type: object
              properties:
                images:
                  type: array
                  items:
                    $ref: '#/components/schemas/image'
              required:
              - images
            - $ref: '#/components/schemas/pagination'
            - $ref: '#/components/schemas/meta'
          examples:
            All:
              $ref: '#/components/examples/images_all'
            Snapshots:
              $ref: '#/components/examples/images_snapshots'
            Distribution:
              $ref: '#/components/examples/images_distribution'
            Custom:
              $ref: '#/components/examples/images_custom'
            Application:
              $ref: '#/components/examples/images_application'
            Tagged:
              $ref: '#/components/examples/images_tagged'
    not_found:
      description: The resource was not found.
      headers:
        ratelimit-limit:
          $ref: '#/components/headers/ratelimit-limit'
        ratelimit-remaining:
          $ref: '#/components/headers/ratelimit-remaining'
        ratelimit-reset:
          $ref: '#/components/headers/ratelimit-reset'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
          example:
            id: not_found
            message: The resource you requested could not be found.
    updated_image:
      description: The response will be a JSON object with a key set to `image`.  The value of this will be an image object containing the standard image attributes.
      headers:
        ratelimit-limit:
          $ref: '#/components/headers/ratelimit-limit'
        ratelimit-remaining:
          $ref: '#/components/headers/ratelimit-remaining'
        ratelimit-reset:
          $ref: '#/components/headers/ratelimit-reset'
      content:
        application/json:
          schema:
            type: object
            properties:
              image:
                $ref: '#/components/schemas/image'
            required:
            - image
          example:
            image:
              id: 7938391
              name: new-image-name
              distribution: Ubuntu
              slug: null
              public: false
              regions:
              - nyc3
              - nyc3
              created_at: '2014-11-14T16:44:03Z'
              min_disk_size: 20
              size_gigabytes: 2.34
              description: ''
              tags: []
              status: available
              error_message: ''
    too_many_requests:
      description: API Rate limit exceeded
      headers:
        ratelimit-limit:
          $ref: '#/components/headers/ratelimit-limit'
        ratelimit-remaining:
          $ref: '#/components/headers/ratelimit-remaining'
        ratelimit-reset:
          $ref: '#/components/headers/ratelimit-reset'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
          example:
            id: too_many_requests
            message: API Rate limit exceeded.
    new_custom_image:
      description: The response will be a JSON object with a key set to `image`.  The value of this will be an image object containing a subset of the standard  image attributes as listed below, including the image's `id` and `status`.  After initial creation, the `status` will be `NEW`. Using the image's id, you  may query the image's status by sending a `GET` request to the  `/v2/images/$IMAGE_ID` endpoint.  When the `status` changes to `available`, the image will be ready for use.
      headers:
        ratelimit-limit:
          $ref: '#/components/headers/ratelimit-limit'
        ratelimit-remaining:
          $ref: '#/components/headers/ratelimit-remaining'
        ratelimit-reset:
          $ref: '#/components/headers/ratelimit-reset'
      content:
        application/json:
          schema:
            properties:
              image:
                $ref: '#/components/schemas/image'
          example:
            image:
              created_at: '2018-09-20T19:28:00Z'
              description: Cloud-optimized image w/ small footprint
              distribution: Ubuntu
              error_message: ''
              id: 38413969
              name: ubuntu-18.04-minimal
              regions: []
              type: custom
              tags:
              - base-image
              - prod
              status: NEW
    unauthorized:
      description: Unauthorized
      headers:
        ratelimit-limit:
          $ref: '#/components/headers/ratelimit-limit'
        ratelimit-remaining:
          $ref: '#/components/headers/ratelimit-remaining'
        ratelimit-reset:
          $ref: '#/components/headers/ratelimit-reset'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
          example:
            id: unauthorized
            message: Unable to authenticate you.
    existing_image:
      description: The response will be a JSON object with a key called `image`.  The value of this will be an image object containing the standard image attributes.
      headers:
        ratelimit-limit:
          $ref: '#/components/headers/ratelimit-limit'
        ratelimit-remaining:
          $ref: '#/components/headers/ratelimit-remaining'
        ratelimit-reset:
          $ref: '#/components/headers/ratelimit-reset'
      content:
        application/json:
          schema:
            type: object
            properties:
              image:
                $ref: '#/components/schemas/image'
            required:
            - image
          example:
            image:
              id: 6918990
              name: 14.04 x64
              distribution: Ubuntu
              slug: ubuntu-16-04-x64
              public: true
              regions:
              - nyc1
              - ams1
              - sfo1
              - nyc2
              - ams2
              - sgp1
              - lon1
              - nyc3
              - ams3
              - nyc3
              created_at: '2014-10-17T20:24:33Z'
              min_disk_size: 20
              size_gigabytes: 2.34
              description: ''
              tags: []
              status: available
              error_message: ''
    server_error:
      description: Server error.
      headers:
        ratelimit-limit:
          $ref: '#/components/headers/ratelimit-limit'
        ratelimit-remaining:
          $ref: '#/components/headers/ratelimit-remaining'
        ratelimit-reset:
          $ref: '#/components/headers/ratelimit-reset'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
          example:
            id: server_error
            message: Unexpected server-side error
  parameters:
    private:
      in: query
      name: private
      description: Used to filter only user images.
      required: false
      schema:
        type: boolean
      example: true
    image_id:
      in: path
      name: image_id
      description: A unique number that can be used to identify and reference a specific image.
      required: true
      schema:
        type: integer
      example: 62137902
    type:
      in: query
      name: type
      description: Filters results based on image type which can be either `application` or `distribution`.
      required: false
      schema:
        type: string
        enum:
        - application
        - distribution
      example: distribution
    per_page:
      in: query
      name: per_page
      required: false
      description: Number of items returned per page
      schema:
        type: integer
        minimum: 1
        default: 20
        maximum: 200
      example: 2
    tag:
      in: query
      name: tag_name
      description: Used to filter images by a specific tag.
      required: false
      schema:
        type: string
      example: base-image
    page:
      in: query
      name: page
      required: false
      description: Which 'page' of paginated results to return.
      schema:
        type: integer
        minimum: 1
        default: 1
      example: 1
  examples:
    images_application:
      description: "**Important:**  \nThe `type` query parameter is not directly related to the `type` attribute.\n"
      value:
        images:
        - id: 7555621
          name: An APP image
          distribution: Fedora
          slug: null
          public: false
          regions:
          - nyc2
          - nyc3
          created_at: '2014-11-04T22:23:02Z'
          type: snapshot
          min_disk_size: 20
          size_gigabytes: 2.34
          description: ''
          tags: []
          status: available
          error_message: ''
        links:
          pages: {}
        meta:
          total: 1
    images_tagged:
      value:
        images:
        - id: 7555621
          name: A simple tagged image
          distribution: CentOS
          slug: null
          public: false
          regions:
          - nyc2
          - nyc3
          created_at: '2014-11-04T22:23:02Z'
          type: snapshot
          min_disk_size: 20
          size_gigabytes: 2.34
          description: ''
          tags:
          - simple-image
          status: available
          error_message: ''
        links:
          pages: {}
        meta:
          total: 1
    images_all:
      value:
        images:
        - id: 7555620
          name: Nifty New Snapshot
          distribution: Ubuntu
          slug: null
          public: false
          regions:
          - nyc2
          - nyc3
          created_at: '2014-11-04T22:23:02Z'
          type: snapshot
          min_disk_size: 20
          size_gigabytes: 2.34
          description: ''
          tags: []
          status: available
          error_message: ''
        - id: 7555621
          name: Another Snapshot
          distribution: Ubuntu
          slug: null
          public: false
          regions:
          - nyc2
          created_at: '2014-11-04T22:23:02Z'
          type: snapshot
          min_disk_size: 20
          size_gigabytes: 2.34
          description: ''
          tags: []
          status: available
          error_message: ''
        - id: 63663980
          name: 20.04 (LTS) x64
          distribution: Ubuntu
          slug: ubuntu-20-04-x64
          public: true
          regions:
          - nyc2
          - nyc3
          created_at: '2020-05-15T05:47:50Z'
          type: snapshot
          min_disk_size: 20
          size_gigabytes: 2.36
          description: ''
          tags: []
          status: available
          error_message: ''
        - id: 7555621
          name: A custom image
          distribution: Arch Linux
          slug: null
          public: false
          regions:
          - nyc3
          created_at: '2014-11-04T22:23:02Z'
          type: custom
          min_disk_size: 20
          size_gigabytes: 2.34
          description: ''
          tags: []
          status: available
          error_message: ''
        - id: 7555621
          name: An APP image
          distribution: Fedora
          slug: null
          public: false
          regions:
          - nyc2
          - nyc3
          created_at: '2014-11-04T22:23:02Z'
          type: snapshot
          min_disk_size: 20
          size_gigabytes: 2.34
          description: ''
          tags: []
          status: available
          error_message: ''
        - id: 7555621
          name: A simple tagged image
          distribution: CentOS
          slug: null
          public: false
          regions:
          - nyc2
          - nyc3
          created_at: '2014-11-04T22:23:02Z'
          type: snapshot
          min_disk_size: 20
          size_gigabytes: 2.34
          description: ''
          tags:
          - simple-image
          status: available
          error_message: ''
        links:
          pages: {}
        meta:
          total: 6
    images_snapshots:
      value:
        images:
        - id: 7555620
          name: Nifty New Snapshot
          distribution: Ubuntu
          slug: null
          public: false
          regions:
          - nyc2
          - nyc3
          created_at: '2014-11-04T22:23:02Z'
          type: snapshot
          min_disk_size: 20
          size_gigabytes: 2.34
          description: ''
          tags: []
          status: available
          error_message: ''
        - id: 7555621
          name: Another Snapshot
          distribution: Ubuntu
          slug: null
          public: false
          regions:
          - nyc2
          created_at: '2014-11-04T22:23:02Z'
          type: snapshot
          min_disk_size: 20
          size_gigabytes: 2.34
          description: ''
          tags: []
          status: available
          error_message: ''
        links:
          pages: {}
        meta:
          total: 2
    images_custom:
      value:
        images:
        - id: 7555621
          name: A custom image
          distribution: Arch Linux
          slug: null
          public: false
          regions:
          - nyc3
          created_at: '2014-11-04T22:23:02Z'
          type: custom
          min_disk_size: 20
          size_gigabytes: 2.34
          description: ''
          tags: []
          status: available
          error_message: ''
        links:
          pages: {}
        meta:
          total: 1
    images_distribution:
      description: "**Important:**  \nThe `type` query parameter is not directly related to the `type` attribute.\nThe main thing to remember here is that DigitalOcean-produced distribution images will have `snapshot` as the type attribute. \n"
      value:
        images:
        - id: 63663980
          name: 20.04 (LTS) x64
          distribution: Ubuntu
          slug: ubuntu-20-04-x64
          public: true
          regions:
          - nyc2
          - nyc3
          created_at: '2020-05-15T05:47:50Z'
          type: snapshot
          min_disk_size: 20
          size_gigabytes: 2.36
          description: ''
          tags: []
          status: available
          error_message: ''
        links:
          pages: {}
        meta:
          total: 1
  headers:
    ratelimit-reset:
      schema:
        type: integer
      example: 1444931833
      description: The time when the oldest request will expire. The value is given in Unix epoch time. See https://developers.digitalocean.com/documentation/v2/#rate-limit for information about how requests expire.
    ratelimit-remaining:
      schema:
        type: integer
      example: 4816
      description: The number of requests in your hourly quota that remain before you hit your request limit. See https://developers.digitalocean.com/documentation/v2/#rate-limit for information about how requests expire.
    ratelimit-limit:
      schema:
        type: integer
      example: 5000
      description: The default limit on number of requests that can be made per hour and per minute. Current rate limits are 5000 requests per hour and 250 requests per minute.
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      description: '## OAuth Authentication


        In order to interact with the DigitalOcean API, you or your application must

        authenticate.


        The DigitalOcean API handles this through OAuth, an open standard for

        authorization. OAuth allows you to delegate access to your account.

        Scopes can be used to grant full access, read-only access, or access to

        a specific set of endpoints.


        You can generate an OAuth token by visiting the [Apps & API](https://cloud.digitalocean.com/account/api/tokens)

        section of the DigitalOcean control panel for your account.


        An OAuth token functions as a complete authentication request. In effect, it

        acts as a substitute for a username and password pair.


        Because of this, it is absolutely **essential** that you keep your OAuth

        tokens secure. In fact, upon generation, the web interface will only display

        each token a single time in order to prevent the token from being compromised.


        DigitalOcean access tokens begin with an identifiable prefix in order to

        distinguish them from other similar tokens.


        - `dop_v1_` for personal access tokens generated in the control panel

        - `doo_v1_` for tokens generated by applications using [the OAuth flow](https://docs.digitalocean.com/reference/api/oauth-api/)

        - `dor_v1_` for OAuth refresh tokens


        ### Scopes


        Scopes act like permissions assigned to an API token. These permissions

        determine what actions the token can perform. You can create API

        tokens that grant read-only access, full access, or limited access to

        specific endpoints by using custom scopes.


        Generally, scopes are designed to match HTTP verbs and common CRUD

        operations (Create, Read, Update, Delete).


        | HTTP Verb | CRUD Operation | Scope |

        |---|---|---|

        | GET | Read | `<resource>:read` |

        | POST | Create | `<resource>:create` |

        | PUT/PATCH | Update | `<resource>:update` |

        | DELETE | Delete | `<resource>:delete` |


        For example, creating a new Droplet by making a `POST` request to the

        `/v2/droplets` endpoint requires the `droplet:create` scope while

        listing Droplets by making a `GET` request to the `/v2/droplets`

        endpoint requires the `droplet:read` scope.


        Each endpoint below specifies which scope is required to access it when

        using custom scopes.


        ### How to Authenticate with OAuth


        In order to make an authenticated request, include a bearer-type

        `Authorization` header containing your OAuth token. All requests must be

        made over HTTPS.


        ### Authenticate with a Bearer Authorization Header


        ```

        curl -X $HTTP_METHOD -H "Authorization: Bearer $DIGITALOCEAN_TOKEN" "https://api.digitalocean.com/v2/$OBJECT"

        ```

        '
